[package]
name = "fs-err"
description = "A simple wrapper around filesystem operations to provide more helpful error messages."
version = "0.1.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
edition = "2018"
repository = "https://github.com/andrewhickman/fs-err"
documentation = "https://docs.rs/fs-error"
categories = ["command-line-interface", "filesystem"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]

[dev-dependencies]
version-sync = "0.8.1"
